"""added scroll labels

Revision ID: 5270087643b1
Revises: 96f10c068905
Create Date: 2020-07-14 23:30:12.618211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5270087643b1'
down_revision = '96f10c068905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('lower_label', sa.String(), nullable=True))
    op.add_column('question', sa.Column('upper_label', sa.String(), nullable=True))
    op.create_index(op.f('ix_question_lower_label'), 'question', ['lower_label'], unique=False)
    op.create_index(op.f('ix_question_upper_label'), 'question', ['upper_label'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_upper_label'), table_name='question')
    op.drop_index(op.f('ix_question_lower_label'), table_name='question')
    op.drop_column('question', 'upper_label')
    op.drop_column('question', 'lower_label')
    # ### end Alembic commands ###
