"""changed references & added responses table

Revision ID: 76763cae5ac8
Revises: 5270087643b1
Create Date: 2020-07-16 13:57:54.353621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76763cae5ac8'
down_revision = '5270087643b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userpollresponse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['poll.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userpollresponse_date'), 'userpollresponse', ['date'], unique=False)
    op.add_column('user_answer', sa.Column('user_poll_response_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'user_answer', type_='foreignkey')
    op.create_foreign_key(None, 'user_answer', 'userpollresponse', ['user_poll_response_id'], ['id'])
    op.drop_column('user_answer', 'user_id')
    op.drop_column('user_answer', 'answer_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answer', sa.Column('answer_date', sa.DATETIME(), nullable=True))
    op.add_column('user_answer', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'user_answer', type_='foreignkey')
    op.create_foreign_key(None, 'user_answer', 'user', ['user_id'], ['id'])
    op.drop_column('user_answer', 'user_poll_response_id')
    op.drop_index(op.f('ix_userpollresponse_date'), table_name='userpollresponse')
    op.drop_table('userpollresponse')
    # ### end Alembic commands ###
